services:
  db:
    image: mariadb:lts-noble
    command: "--default-authentication-plugin=my_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
     - MYSQL_DATABASE=bank
     - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  core:
    build:
      context: core
      target: builder
    restart: always
    secrets:
      - db-password
    networks:
      - private
      - public
    depends_on:
      - db

volumes:
  db-data:
secrets:
  db-password:
    file: db/db-password.txt
networks:
  private:
  public:
